In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [9]:
veda_distortion_matr = np.array([[2.51859320e+03, 0.00000000e+00, 1.61308333e+03],
 [0.00000000e+00, 2.64386474e+03, 2.29079218e+03],
 [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

veda_distortion_coeff = np.array([[-0.00225511, -0.3730469, -0.02478544, -0.01167432, 0.52906048]])

veda_rotation_vectors = [np.array([[-0.22860323], [-0.56769533], [-2.02694221]]),
                        np.array([[-0.37236873], [-0.00972739], [-0.03417783]]), 
                        np.array([[-0.57144478], [ 0.74930948], [ 2.45519884]]), 
                        np.array([[-0.4700357 ], [ 0.59818767], [-0.25136095]])]
veda_translation_vectors = 

 Translation Vectors:
(array([[ 1.10049952],
       [-0.30945937],
       [10.34585432]]), array([[-3.42846412],
       [-4.46120217],
       [17.68728685]]), array([[ 0.81968688],
       [-1.00290035],
       [15.31412188]]), array([[-1.44894378],
       [-6.28270033],
       [20.41398239]]))
ashish_distortion = np.array([[2.73883498e+03, 0.00000000e+00, 1.87701862e+03],
 [0.00000000e+00, 2.71781331e+03,2.09937064e+03],
 [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

IndentationError: unexpected indent (3606427562.py, line 16)

In [8]:
print(veda_distortion-ashish_distortion)

[[-220.24178    0.      -263.93529]
 [   0.       -73.94857  191.42154]
 [   0.         0.         0.     ]]


In [22]:
aditya_inside_matrix = np.array([[3.10509613e+03, 0.00000000e+00, 2.00838349e+03],
 [0.00000000e+00, 3.10200975e+03, 1.09013914e+03],
 [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

aditya_outside_matrix = np.array([[3.05128562e+03, 0.00000000e+00, 2.01896570e+03],
 [0.00000000e+00, 3.04687872e+03, 1.09365105e+03],
 [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

aditya_trial_2 = np.array([[3.56675878e+03, 0.00000000e+00, 1.30715772e+03],
 [0.00000000e+00, 3.54011576e+03, 1.11736970e+03],
 [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [23]:
(aditya_trial_2 - aditya_trial_2_cleaned)[0,0]/aditya_trial_2[0,0] * 100

0.0